server:
  port: 8001
spring:
  application:
    name: StreamWithRabbitMQConsumer
  rabbitmq:
    addresses: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        input:
          destination: pipe
          group: A
          consumer:
            partitioned: true
#     消费者实例数量
      instance-count: 2
#      消费者ID
      instance-index: 0
